baseURL = "https://mdb.io/"
languageCode = "en-us"
title = "Matt Bailey"
copyright = "©"

# Code Highlight
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 3

[module]
[[module.imports]]
path = "github.com/athul/archie"

[params]
mode = "auto" # color-mode → light,dark or auto

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3
