baseURL = "https://mdb.io/"
languageCode = "en-us"
title = "hi, i am matt bailey."
paginate=3 # articles per page
copyright = "© me"

# Code Highlight
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[module]
  [[module.imports]]
    path = "github.com/athul/archie"

[params]
	mode="auto" # color-mode → light,dark or auto

[[menu.main]]
name = "About"
url = "/about"
weight = 3
