baseURL = "https://mdb.io/"
languageCode = "en-us"
title = "Matt Bailey"
paginate=3 # articles per page
copyright = "©"

# Code Highlight
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[module]
  [[module.imports]]
    path = "github.com/athul/archie"

[params]
	mode="auto" # color-mode → light,dark or auto

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3
